!
!       pi2d fortran interface
!
	integer, external :: pi2d_init
	integer, external :: pi2d_finalize
	integer, external :: pi2d_setattrib
	integer, external :: pi2d_setcord
	integer, external :: pi2d_createlut
	integer, external :: pi2d_setlutcolor
	integer, external :: pi2d_setlutattrib
	integer, external :: pi2d_draws
	integer, external :: pi2d_drawv
	integer, external :: pi2d_output
	integer, external :: pi2d_importattrib
	integer, external :: pi2d_exportattrib
!
